[package]
name = "iif"
description = "Returns one of two parts, depending on the evaluation of an expression."
version = "1.1.0"
authors = ["hardliner66 <hardliner66@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/hardliner66/iif"
